"""AST peephole that hoists CuTe warp reductions out of constexpr V-loops.

CuTe softmax/online-reduction kernels generated by Helion currently emit a
constexpr V-loop (``for vec_lane in cutlass.range_constexpr(V): ...``)
that wraps the whole per-tile body — including warp-reduction calls.  That
gives 4x SHFL traffic for V=4: each tile iteration calls
``cute.arch.warp_reduction_*`` V times in serial, even though the user's
``torch.amax(values, dim=1)`` is conceptually ONE reduce across the whole
tile.  Online softmax makes the V-serialized reduction equivalent to a
single reduce over all V*W lanes, so the pattern is correct — just
expensive.

This pass detects::

    for VEC_LANE in cutlass.range_constexpr(V):
        ... pre-reduce ...
        RESULT = <cast>(cute.arch.warp_reduction_<op>(INPUT, threads_in_group=T))
        ... uses RESULT ...
        # optional: another warp_reduction_<op2> ...

and rewrites it to::

    acc = identity
    for VEC_LANE in cutlass.range_constexpr(V):
        ... pre-reduce ...
        acc = combine(acc, INPUT)
    RESULT = <cast>(cute.arch.warp_reduction_<op>(acc, threads_in_group=T))
    ... uses RESULT (run ONCE per outer iter) ...
    # (next reduce: similar V-fold + ONE warp_reduce + ONCE post)

The reduce now runs once per outer iter (saves V-1 warp reductions per
reduce), and the post-reduce scalar updates (mi_next, alpha, di update,
mi update) run once instead of V times.

The pass is conservative: it only triggers for the well-defined "V-loop
contains a warp_reduction" pattern, and bails out if the structure is
unexpected.
"""

from __future__ import annotations

import ast
from typing import cast

from ..ast_extension import statement_from_string
from ._ast_pass_utils import _assignment_lhs_name
from ._ast_pass_utils import _names_read

# Warp-reduction call attribute names recognised by this pass.  Each maps
# to the identity element used for the per-thread V-fold accumulator.
_REDUCE_IDENTITY: dict[str, str] = {
    "warp_reduction_sum": "0",
    "warp_reduction_max": "float('-inf')",
    "warp_reduction_min": "float('inf')",
}


# Per-reduction combine op used to fold V values into the accumulator
# before the single warp reduce.  ``a`` is the existing accumulator,
# ``b`` is the per-iter contribution.
_REDUCE_COMBINE: dict[str, str] = {
    "warp_reduction_sum": "({a}) + ({b})",
    "warp_reduction_max": "max(({a}), ({b}))",
    "warp_reduction_min": "min(({a}), ({b}))",
}


# The GROUPED reduce helpers carry their op in a STRING ARGUMENT rather than in the
# function name: ``_cute_grouped_reduce_warp(acc, 'sum', identity, lane, ...)`` and
# ``_cute_grouped_reduce_shared_two_stage(acc, 'max', ...)``.  Map those op strings onto
# the same ``warp_reduction_<op>`` keys the tables above use, so one matcher covers all
# three emitted forms.
#
# WHY THIS MATTERS (MEASURED, LEDGER E018).  This pass used to match ONLY
# ``cute.arch.warp_reduction_*``, so whenever ``_finalize_lane_reduce_marker``
# (``tile_strategy.py:365-416``) chose a grouped or two-stage combine instead of the raw
# warp form, the hoist silently did not fire, the whole online-merge body stayed inside
# ``range_constexpr(V)``, and BOTH exponentials of the online recurrence ran V times per V
# elements -- 2.0 exp/element instead of 1 + 1/V.  On ``cross_entropy_online`` at
# M=32768 N=4096 that boundary is worth 3.6x: configs where the hoist fires measure
# 1.125 exp/element and 0.820x of quack, configs where it does not measure 2.0 and 0.230x.
# ``03_FINDINGS.md`` section 3 measured exp2 issue rate as this kernel's limiter and
# concluded the online recurrence "needs a SECOND exp per element" -- true of the
# algorithm, but NOT of the emitted code once this pass fires.
_GROUPED_REDUCE_FUNCS: frozenset[str] = frozenset(
    {"_cute_grouped_reduce_warp", "_cute_grouped_reduce_shared_two_stage"}
)

_GROUPED_OP_TO_KEY: dict[str, str] = {
    "sum": "warp_reduction_sum",
    "max": "warp_reduction_max",
    "min": "warp_reduction_min",
}


def _looks_like_warp_reduce_call(node: ast.AST) -> tuple[str, ast.expr] | None:
    """Recognise any of helion's three emitted warp/group reduce forms.

    Returns ``("warp_reduction_<op>", INPUT)``, where ``INPUT`` is the value being
    reduced, or None.  The three forms:

    * ``cute.arch.warp_reduction_<op>(INPUT, threads_in_group=T)`` -- the raw single-warp
      primitive, op in the function name (``tile_strategy.py:419-429``);
    * ``_cute_grouped_reduce_warp(INPUT, '<op>', identity, lane, ...)`` -- strided groups
      within one warp, op in argument 1 (``tile_strategy.py:296-316``);
    * ``_cute_grouped_reduce_shared_two_stage(INPUT, '<op>', ...)`` -- cross-warp via
      SMEM, op in argument 1 (``tile_strategy.py:319-362``).

    All three are V-fold-hoistable for the same reason: the fold is over the SAME
    associative op that the reduce itself applies, so folding V values into a per-thread
    accumulator first and reducing once is equivalent to reducing V times.  The pass is
    unchanged downstream -- only the set of recognised shapes grows.
    """
    if not isinstance(node, ast.Call):
        return None
    func = node.func
    # Form 1: op in the attribute name, under a ``.arch`` namespace.
    if isinstance(func, ast.Attribute):
        if func.attr not in _REDUCE_IDENTITY:
            return None
        val = func.value
        if not (isinstance(val, ast.Attribute) and val.attr == "arch"):
            return None
        if not node.args:
            return None
        return func.attr, node.args[0]
    # Forms 2 and 3: a bare helper name, op in the second positional argument.
    if isinstance(func, ast.Name) and func.id in _GROUPED_REDUCE_FUNCS:
        if len(node.args) < 2:
            return None
        op_arg = node.args[1]
        if not (isinstance(op_arg, ast.Constant) and isinstance(op_arg.value, str)):
            return None
        key = _GROUPED_OP_TO_KEY.get(op_arg.value)
        if key is None:
            # ``prod`` has a grouped helper but no entry in ``_REDUCE_IDENTITY`` /
            # ``_REDUCE_COMBINE``, so it is not hoistable by this pass.  Decline rather
            # than fold it with the wrong identity.
            return None
        return key, node.args[0]
    return None


def _find_warp_reduce_in_expr(
    node: ast.AST,
) -> tuple[str, ast.expr, ast.Call] | None:
    """Find the first warp-reduction call inside ``node`` (depth-first).

    Returns ``(op, input_expr, call_node)`` or None.
    """
    if isinstance(node, ast.Call):
        match = _looks_like_warp_reduce_call(node)
        if match is not None:
            op, inp = match
            return op, inp, node
    for child in ast.iter_child_nodes(node):
        result = _find_warp_reduce_in_expr(child)
        if result is not None:
            return result
    return None


def _is_constexpr_v_loop(node: ast.stmt) -> tuple[ast.For, int] | None:
    """If ``node`` is ``for X in cutlass.range_constexpr(V): ...``, return
    ``(node, V)``.  Otherwise None.
    """
    if not isinstance(node, ast.For):
        return None
    iter_node = node.iter
    if not (
        isinstance(iter_node, ast.Call)
        and isinstance(iter_node.func, ast.Attribute)
        and iter_node.func.attr == "range_constexpr"
        and isinstance(iter_node.func.value, ast.Name)
        and iter_node.func.value.id == "cutlass"
    ):
        return None
    if not iter_node.args:
        return None
    arg = iter_node.args[0]
    if not (isinstance(arg, ast.Constant) and isinstance(arg.value, int)):
        return None
    return node, arg.value


def _names_written(node: ast.stmt) -> set[str]:
    """Collect names written by an assignment statement (LHS Name targets)."""
    written: set[str] = set()
    if isinstance(node, ast.Assign):
        for target in node.targets:
            if isinstance(target, ast.Name):
                written.add(target.id)
            elif isinstance(target, (ast.Tuple, ast.List)):
                for elt in target.elts:
                    if isinstance(elt, ast.Name):
                        written.add(elt.id)
    return written


def _assignment_rhs(node: ast.stmt) -> ast.expr | None:
    if isinstance(node, ast.Assign):
        return node.value
    return None


def _compute_dependency_closure(
    body: list[ast.stmt],
    target_indices: set[int],
) -> set[int]:
    """Find all stmt indices that contribute to producing values used by
    statements at ``target_indices`` (transitive backward dep).

    Returns the closure including ``target_indices`` themselves.
    """
    # For each statement, gather the names it writes; record the LATEST def
    # for each name (last assignment wins, since that's what subsequent
    # reads would see).  For SSA-like dependency closure, we want: for each
    # name used by a stmt at idx, find the most recent prior stmt that
    # wrote that name.  Then chain.
    def_history: list[dict[str, int]] = []
    current: dict[str, int] = {}
    for i, stmt in enumerate(body):
        # Snapshot the def map BEFORE this stmt.
        def_history.append(dict(current))
        # Now update with this stmt's writes.
        for name in _names_written(stmt):
            current[name] = i

    # Now do BFS backward from target_indices.
    closure: set[int] = set(target_indices)
    worklist: list[int] = list(target_indices)
    while worklist:
        i = worklist.pop()
        stmt = body[i]
        defs_before = def_history[i]
        for name in _names_read(stmt):
            j = defs_before.get(name)
            if j is not None and j not in closure:
                closure.add(j)
                worklist.append(j)
    return closure


def _try_hoist_one_vloop(
    vloop: ast.For,
    v: int,
    acc_name_counter: list[int],
    running_sums: set[str],
) -> list[ast.stmt] | None:
    """Try to hoist warp reductions out of a single constexpr V-loop.

    Returns the new list of statements that REPLACES the V-loop, or None if
    the pattern doesn't match safely.  All AST mutations are performed on
    deep-copied nodes, so a failed attempt leaves the original V-loop
    untouched.
    """
    body = vloop.body
    vec_lane_var: str | None = None
    if isinstance(vloop.target, ast.Name):
        vec_lane_var = vloop.target.id

    # ---- VALIDATION PHASE: no mutations yet. ----

    # Find all warp_reduction calls. Each is (idx, op, input_name).
    reduce_validate: list[tuple[int, str, str]] = []
    for idx, stmt in enumerate(body):
        rhs = _assignment_rhs(stmt)
        lhs = _assignment_lhs_name(stmt)
        if rhs is None or lhs is None:
            continue
        found = _find_warp_reduce_in_expr(rhs)
        if found is None:
            continue
        op, input_expr, _call = found
        if not isinstance(input_expr, ast.Name):
            return None
        reduce_validate.append((idx, op, input_expr.id))

    if not reduce_validate:
        return None

    # V-dependence flow analysis (forward pass).
    #
    # A statement is "V-dependent" if its result varies per V-lane iteration.
    # Reads of the V-lane variable or of any V-dep name make a stmt V-dep.
    # CRUCIALLY: a warp-reduction statement's OUTPUT is scalar (one value
    # per warp, not per V-lane).  After hoisting, the reduce runs once and
    # downstream uses of its output are scalar — so we do NOT propagate
    # V-dep through reduce statements.
    reduce_stmt_indices = {idx for idx, _op, _name in reduce_validate}
    v_dependent: set[int] = set()
    if vec_lane_var is not None:
        v_defined_names: set[str] = set()
        for i, stmt in enumerate(body):
            reads = _names_read(stmt)
            if vec_lane_var in reads or (reads & v_defined_names):
                v_dependent.add(i)
                if i not in reduce_stmt_indices:
                    # Only non-reduce stmts produce V-dep outputs.
                    v_defined_names.update(_names_written(stmt))

    # Validate each reduce: input must be V-dependent (otherwise pointless),
    # and have a clear definition.
    for idx, _op, input_name in reduce_validate:
        input_def_idx = -1
        for j in range(idx - 1, -1, -1):
            if input_name in _names_written(body[j]):
                input_def_idx = j
                break
        if input_def_idx < 0:
            return None
        if input_def_idx not in v_dependent:
            return None
        rhs = _assignment_rhs(body[input_def_idx])
        if rhs is None:
            return None

    # Trailing stmts after last reduce: bail if any are V-dependent.
    last_reduce_idx = reduce_validate[-1][0]
    for i in range(last_reduce_idx + 1, len(body)):
        if i in v_dependent:
            return None

    # Compute closure for each reduce's input.
    closures: list[set[int]] = []
    for idx, _op, input_name in reduce_validate:
        input_def_idx = -1
        for j in range(idx - 1, -1, -1):
            if input_name in _names_written(body[j]):
                input_def_idx = j
                break
        closure = _compute_dependency_closure(body, {input_def_idx})
        closures.append(closure)
    all_closures: set[int] = set()
    for c in closures:
        all_closures |= c

    # V-dependent stmts that no reduce's closure reaches ("orphans").  These
    # used to be an unconditional BAIL, on the reasoning that hoisting would
    # lose them -- but they are not lost if they are carried into a V-loop,
    # which is exactly where they already live.
    #
    # ⚠ WHY THIS MATTERS (LEDGER E065): a bounds mask that the tile strategy
    # proves vacuous takes the lane-index stmt out of every closure with it.
    # The masked form is
    #
    #     indices_2 = lane_base + Int32(vec_lane)      # V-dep
    #     mask_1    = indices_2 < N                    # reads indices_2
    #     values    = <load> if mask_0 and mask_1 else <identity>
    #
    # so ``indices_2`` reaches the reduce input THROUGH the mask and lands in
    # the closure.  Elide the (provably true) mask and the chain breaks:
    # ``values`` no longer reads ``indices_2``, the lane-index stmt becomes an
    # orphan, and this pass declined on the SIMPLER of the two shapes.  Three
    # passes keyed on that wrapper (this one, ``merge_sibling_v_loops``, and
    # the FMA-scale hoist) went inert at once.
    #
    # Assigning each orphan to the V-loop of the first reduce that FOLLOWS it
    # preserves both its trip count (V, unchanged) and its order relative to
    # the other V-loop stmts, since the body is emitted in original index
    # order.  A trailing orphan is impossible: the check above already bails on
    # any V-dep stmt after the last reduce.
    #
    # Only a PURE ``name = expr`` orphan is carried.  A bare-expression orphan
    # is a gmem store (``(ptr).store(v)``) or another side effect, and moving
    # one across a reduce would reorder it against the reduce -- decline, as
    # before.
    #
    # A pure orphan whose LHS NOTHING in the body reads is simply DROPPED, not
    # carried.  That is not an optimisation for its own sake: it keeps the two
    # sweeps' V-loop bodies TEXTUALLY IDENTICAL in their prefix, which is the
    # precondition ``merge_sibling_v_loops`` matches on
    # (``common_prefix_len == 0`` -> no merge).  The mask elision leaves the
    # lane-index stmt live in the REDUCE sweep and dead in the CONSUME sweep,
    # so carrying a dead one would fix this pass and keep the next one inert.
    body_reads: set[str] = set()
    for s in body:
        body_reads |= _names_read(s)

    orphan_v_members: list[set[int]] = [set() for _ in reduce_validate]
    for i in sorted(v_dependent - all_closures - reduce_stmt_indices):
        lhs_name = _assignment_lhs_name(body[i])
        if lhs_name is None:
            return None
        if lhs_name not in body_reads:
            continue  # dead in this V-loop -- drop it
        for reduce_pos, (r_idx, _op, _name) in enumerate(reduce_validate):
            if i < r_idx:
                orphan_v_members[reduce_pos].add(i)
                break
        else:
            # Unreachable given the trailing-V-dep bail above; keep the
            # conservative decline rather than silently dropping a statement.
            return None

    # ---- COMMIT PHASE: build new statements. ----
    new_stmts: list[ast.stmt] = []

    # Re-find call_nodes and stmts on a re-parsed copy of the body so we
    # don't mutate the original V-loop's children.  ``ast.unparse`` +
    # ``ast.parse`` avoids the ``copy.deepcopy`` failure on ExtendedAST.
    body_copy: list[ast.stmt] = []
    for s in body:
        text = ast.unparse(s)
        parsed = ast.parse(text).body[0]
        body_copy.append(parsed)
    reduce_info_copy: list[tuple[int, str, str, str, ast.Call, ast.stmt]] = []
    for idx, stmt in enumerate(body_copy):
        rhs = _assignment_rhs(stmt)
        lhs = _assignment_lhs_name(stmt)
        if rhs is None or lhs is None:
            continue
        found = _find_warp_reduce_in_expr(rhs)
        if found is None:
            continue
        op, input_expr, call_node = found
        # DECLINE rather than assert.  This used to be
        # ``assert isinstance(input_expr, ast.Name)``, which was safe while the matcher
        # only accepted ``cute.arch.warp_reduction_*`` (whose input is always a hoisted
        # temp name).  Now that the grouped/two-stage forms are matched too, the reduced
        # value can be an arbitrary expression, and an assert would turn a
        # missed-optimisation into a compiler crash.  The V-fold accumulator has to name
        # the input to combine it, so a non-Name input is simply not hoistable here.
        if not isinstance(input_expr, ast.Name):
            continue
        reduce_info_copy.append((idx, lhs, op, input_expr.id, call_node, stmt))

    # Build a schedule:
    #  - For each stmt in body, decide whether it's scalar (emit once) or
    #    V-dep (emit inside a V-loop).  V-dep stmts get assigned to whichever
    #    reduce's V-loop they belong to (based on closure membership).  A
    #    V-dep stmt MAY belong to multiple V-loops (e.g. ``values`` extracted
    #    from the load is read by both reduces).
    #  - Reduce stmts are emitted after their V-loop in scalar scope.
    #  - Scalar stmts not in any closure go where they appear in original
    #    order, relative to the surrounding reduces.

    # For each reduce, determine which V-dep stmts belong in its V-loop.
    # Exclude all reduce stmts from V-loop bodies — they've been hoisted to
    # scalar scope (the reduce call produces a scalar that downstream code
    # uses; running it inside the V-loop would re-do the warp reduce V times,
    # which defeats the whole purpose of this pass).
    reduce_stmt_indices_in_body = {
        r_idx for r_idx, _l, _o, _n, _c, _s in reduce_info_copy
    }
    v_loop_members: list[set[int]] = []
    for reduce_pos, c in enumerate(closures):
        members = (c & v_dependent) - reduce_stmt_indices_in_body
        # Carry this reduce's orphan V-dep stmts (see the note above) into its
        # V-loop so eliding a provably-vacuous mask cannot make the pass inert.
        members |= orphan_v_members[reduce_pos] - reduce_stmt_indices_in_body
        v_loop_members.append(members)

    # Compute "scalar emission position" for each scalar stmt: emit after
    # the last reduce idx < stmt_idx (or before all reduces if none).  We
    # mark each scalar stmt with a "phase" number: 0 = before first reduce,
    # k = after reduce (k-1).
    def scalar_phase(i: int) -> int:
        phase = 0
        for r_idx, _l, _o, _n, _c, _s in reduce_info_copy:
            if r_idx < i:
                phase += 1
            else:
                break
        return phase

    # Group scalar stmts by phase.
    phase_scalars: dict[int, list[int]] = {}
    for i in range(len(body_copy)):
        is_reduce = any(r_idx == i for r_idx, *_ in reduce_info_copy)
        if i in v_dependent or is_reduce:
            continue
        phase = scalar_phase(i)
        phase_scalars.setdefault(phase, []).append(i)

    # Emit phase 0 scalars (before first reduce).
    for j in sorted(phase_scalars.get(0, [])):
        new_stmts.append(body_copy[j])

    for reduce_pos, (
        idx,
        _lhs,
        op,
        input_name,
        call_node,
        reduce_stmt,
    ) in enumerate(reduce_info_copy):
        # Find input def idx in body_copy.
        input_def_idx = -1
        for j in range(idx - 1, -1, -1):
            if input_name in _names_written(body_copy[j]):
                input_def_idx = j
                break
        assert input_def_idx >= 0
        input_def_rhs = _assignment_rhs(body_copy[input_def_idx])
        assert input_def_rhs is not None

        identity = _REDUCE_IDENTITY[op]
        combine_template = _REDUCE_COMBINE[op]
        # Decide how to hoist the reduce.  Three cases:
        #
        #  (b) The input is a matmul-fallback PER-THREAD RUNNING SUM, flagged
        #      authoritatively by the producer (``_emit_cute_matmul`` records
        #      the ``dot_acc`` var on the DeviceFunction).  Such a value
        #      already accumulates across V-lanes inside its own
        #      ``acc = acc + product`` def, so a per-thread partial + ONE
        #      cross-thread sum reduce is exactly the full sum: keep the def in
        #      the loop and reduce its FINAL value once.  V-folding it again
        #      would double-count.
        #
        #  (c) The input is loop-carried (its in-loop def reads itself) but NOT
        #      a flagged running sum — a rescaled / non-sum recurrence such as
        #      ``di = di * alpha + ...`` or ``mi = maximum(mi, ...)``.  Neither
        #      the V-fold (would fold the carried value) nor reduce-once (sum
        #      identity doesn't hold) is valid, so leave the V-loop untouched.
        #
        #  (a) Otherwise the input is a fresh per-lane value (softmax /
        #      layernorm ``amax``/``sum``): build a ``_helion_vfold_acc`` and
        #      fold each lane in, then ONE warp reduce.  [the original path]
        input_def = body_copy[input_def_idx]
        input_is_running_sum = input_name in running_sums
        if not input_is_running_sum and input_name in _names_read(input_def):
            return None  # case (c): loop-carried but not a known running sum
        input_is_loop_carried = input_is_running_sum

        vloop_body: list[ast.stmt] = []
        v_members = sorted(v_loop_members[reduce_pos])
        if input_is_loop_carried:
            acc_name = input_name
            for j in v_members:
                vloop_body.append(body_copy[j])
        else:
            acc_name = f"_helion_vfold_acc_{acc_name_counter[0]}"
            acc_name_counter[0] += 1
            acc_dtype = _infer_input_dtype(input_def_rhs)
            if acc_dtype is None:
                return None
            acc_init_expr = f"{acc_dtype}({identity})"
            new_stmts.append(statement_from_string(f"{acc_name} = {acc_init_expr}"))

            # V-loop body: all V-dep stmts in this reduce's closure, in
            # original order.  When we hit input_def_idx, also emit acc
            # combine after it.  Rewrite the acc combine's input expression's
            # cast wrapper to use the acc dtype (avoids a double cast on
            # fp16/bf16 inputs being promoted to fp32 acc).  Keep the
            # original input def stmt — it may be read by later V-loop stmts
            # (the dependency closure can include paths through it), and the
            # CuTe DSL will DCE it if unused.
            for j in v_members:
                vloop_body.append(body_copy[j])
                if j == input_def_idx:
                    input_rhs = _assignment_rhs(body_copy[j])
                    assert input_rhs is not None
                    promoted_rhs = _rewrite_cast_wrapper(input_rhs, acc_dtype)
                    rhs_text = ast.unparse(promoted_rhs)
                    combine_expr = combine_template.format(a=acc_name, b=rhs_text)
                    vloop_body.append(
                        statement_from_string(f"{acc_name} = {combine_expr}")
                    )

        target_text = ast.unparse(vloop.target)
        iter_text = ast.unparse(vloop.iter)
        new_vloop_template = ast.parse(
            f"for {target_text} in {iter_text}:\n    pass"
        ).body[0]
        assert isinstance(new_vloop_template, ast.For)
        new_vloop_template.body = vloop_body
        ast.copy_location(new_vloop_template, vloop)
        ast.fix_missing_locations(new_vloop_template)
        new_stmts.append(new_vloop_template)

        # Emit the reduce stmt with input -> acc.
        new_reduce_stmt = _replace_reduce_input(reduce_stmt, call_node, acc_name)
        if new_reduce_stmt is None:
            return None
        new_stmts.append(new_reduce_stmt)

        # Emit phase (reduce_pos + 1) scalars.
        for j in sorted(phase_scalars.get(reduce_pos + 1, [])):
            new_stmts.append(body_copy[j])

    return new_stmts


def _rewrite_cast_wrapper(rhs: ast.expr, new_dtype: str) -> ast.expr:
    """Rewrite a narrowing dtype wrapper (e.g. ``cutlass.Float16(x)``) to
    use ``new_dtype`` instead, recursing into IfExp branches and arg lists.

    For ``cutlass.Float16(values) if mask else cutlass.Float16(-inf)``,
    returns ``cutlass.Float32(values) if mask else cutlass.Float32(-inf)``.
    Falls back to ``new_dtype(<original>)`` if the structure isn't a
    recognised cast wrapper.
    """
    if isinstance(rhs, ast.IfExp):
        new_body = _rewrite_cast_wrapper(rhs.body, new_dtype)
        new_orelse = _rewrite_cast_wrapper(rhs.orelse, new_dtype)
        return ast.IfExp(test=rhs.test, body=new_body, orelse=new_orelse)
    if (
        isinstance(rhs, ast.Call)
        and isinstance(rhs.func, ast.Attribute)
        # Same structural test as ``_infer_input_dtype``: a dtype CONSTRUCTOR
        # is ``<Name>.<dtype>(x)``.  ``cutlass.Uint16(x).bitcast(...)`` shares
        # the text prefix but replacing it would DROP the bitcast and reduce
        # the raw storage bits (LEDGER E065).
        and isinstance(rhs.func.value, ast.Name)
        and ast.unparse(rhs.func).startswith("cutlass.Float")
    ):
        # Rewrite the cast wrapper to use new_dtype.
        # Parse "<new_dtype>(<args>)" template.
        args_text = ", ".join(ast.unparse(a) for a in rhs.args)
        new_call = ast.parse(f"{new_dtype}({args_text})").body[0]
        assert isinstance(new_call, ast.Expr)
        return new_call.value
    # Otherwise wrap with new_dtype.
    return ast.parse(f"{new_dtype}({ast.unparse(rhs)})").body[0].value  # type: ignore[union-attr]


def _infer_input_dtype(rhs: ast.expr) -> str | None:
    """Detect the dtype wrapper at the outermost level of ``rhs``.

    Examples:
        ``cutlass.Float32(x)`` → "cutlass.Float32"
        ``cutlass.Float16(x) if cond else cutlass.Float16(-inf)`` → "cutlass.Float16"
        ``cute.math.exp2(...)`` → None (no explicit wrapper)
    """
    if isinstance(rhs, ast.IfExp):
        # Assume body and orelse share the same outer wrapper.
        return _infer_input_dtype(rhs.body)
    # ``cutlass.Uint16(<vec>[vi]).bitcast(cutlass.Float16)`` -- the vec-hoist
    # load.  Its VALUE dtype is the bitcast TARGET, not the storage type the
    # chain starts from, so read the argument.
    #
    # ⚠ Reachable only in the UNMASKED form (LEDGER E065).  With a mask, the
    # reduce consumed a ``_mask_to = cutlass.Float16(values) if mask else ...``
    # temp whose wrapper is a plain dtype call, so this function never saw the
    # bitcast chain.  Elide the mask and the chain becomes the reduce input
    # directly -- at which point the ``startswith("cutlass.Uint")`` test below
    # matched the unparse of the whole ``cutlass.Uint16(...).bitcast``
    # ATTRIBUTE and returned it as if it were a dtype name, so the emitted
    # combine was ``max(acc, cutlass.Uint16(v).bitcast(cutlass.Uint16(v).bitcast(
    # cutlass.Float16)))``.  Latent nonsense, not a decline.
    if (
        isinstance(rhs, ast.Call)
        and isinstance(rhs.func, ast.Attribute)
        and rhs.func.attr == "bitcast"
        and len(rhs.args) == 1
    ):
        return _infer_input_dtype_from_dtype_expr(rhs.args[0])
    if (
        isinstance(rhs, ast.Call)
        and isinstance(rhs.func, ast.Attribute)
        # A DTYPE CONSTRUCTOR only: ``cutlass.Float16(x)``, whose callee is
        # ``<Name>.<attr>``.  A chained method call such as
        # ``cutlass.Uint16(x).bitcast`` unparses with the same prefix but is
        # not a dtype, so match on structure rather than on the text.
        and isinstance(rhs.func.value, ast.Name)
    ):
        func_text = ast.unparse(rhs.func)
        # Promote fp16/bf16 accumulators to fp32 for better perf and accuracy:
        # the downstream uses convert to fp32 anyway, and fp16 max is no
        # cheaper than fp32 max on B200.  Sum benefits from fp32 to avoid
        # losing precision over the V-fold.
        if func_text in ("cutlass.Float16", "cutlass.BFloat16"):
            return "cutlass.Float32"
        if func_text.startswith("cutlass.Float"):
            return func_text
        if func_text.startswith("cutlass.Int"):
            return func_text
        if func_text.startswith("cutlass.Uint"):
            return func_text
    # Conservative default — sufficient for sum/max in fp32 accumulators.
    return "cutlass.Float32"


def _infer_input_dtype_from_dtype_expr(node: ast.expr) -> str:
    """Map a bare dtype expression (``cutlass.Float16``) to the accumulator
    dtype, applying the same fp16/bf16 -> fp32 promotion as
    ``_infer_input_dtype``.
    """
    text = ast.unparse(node)
    if text in ("cutlass.Float16", "cutlass.BFloat16"):
        return "cutlass.Float32"
    if text.startswith(("cutlass.Float", "cutlass.Int", "cutlass.Uint")):
        return text
    return "cutlass.Float32"


def _replace_reduce_input(
    reduce_stmt: ast.stmt, call_node: ast.Call, acc_name: str
) -> ast.stmt | None:
    """Return a copy of ``reduce_stmt`` with ``call_node``'s first arg replaced
    by ``Name(acc_name)``.
    """
    if not isinstance(reduce_stmt, ast.Assign):
        return None

    class _InputRewriter(ast.NodeTransformer):
        def __init__(self) -> None:
            self.done = False

        def visit_Call(self, node: ast.Call) -> ast.AST:
            if node is call_node and not self.done:
                self.done = True
                new_args = [ast.Name(id=acc_name, ctx=ast.Load()), *node.args[1:]]
                new_call = ast.Call(
                    func=node.func, args=new_args, keywords=node.keywords
                )
                return ast.copy_location(new_call, node)
            return cast("ast.AST", self.generic_visit(node))

    rewriter = _InputRewriter()
    new_stmt = rewriter.visit(reduce_stmt)
    if not rewriter.done:
        return None
    assert isinstance(new_stmt, ast.stmt)
    ast.fix_missing_locations(new_stmt)
    return new_stmt


def _hoist_in_body(
    body: list[ast.stmt], acc_counter: list[int], running_sums: set[str]
) -> list[ast.stmt]:
    """Walk ``body`` recursively; for each constexpr V-loop containing warp
    reductions, replace it with the V-fold + hoisted-reduce form.
    """
    new_body: list[ast.stmt] = []
    for stmt in body:
        if isinstance(stmt, ast.For):
            stmt.body = _hoist_in_body(stmt.body, acc_counter, running_sums)
            stmt.orelse = _hoist_in_body(stmt.orelse, acc_counter, running_sums)
            match = _is_constexpr_v_loop(stmt)
            if match is not None:
                vloop, v = match
                replacement = _try_hoist_one_vloop(vloop, v, acc_counter, running_sums)
                if replacement is not None:
                    new_body.extend(replacement)
                    continue
            new_body.append(stmt)
        elif isinstance(stmt, ast.If):
            stmt.body = _hoist_in_body(stmt.body, acc_counter, running_sums)
            stmt.orelse = _hoist_in_body(stmt.orelse, acc_counter, running_sums)
            new_body.append(stmt)
        elif isinstance(stmt, (ast.With, ast.FunctionDef)):
            stmt.body = _hoist_in_body(stmt.body, acc_counter, running_sums)
            new_body.append(stmt)
        else:
            new_body.append(stmt)
    return new_body


def hoist_warp_reduce_from_vloop(
    body: list[ast.stmt],
    *,
    running_sum_accumulators: set[str] | None = None,
) -> list[ast.stmt]:
    """Apply the hoist pass to a list of kernel-body statements.

    Returns the (possibly modified) body.  Safe to call on any kernel body
    — only rewrites the well-defined "warp reduction inside constexpr V-loop"
    pattern.

    ``running_sum_accumulators`` is the set of matmul-fallback per-thread
    running-sum variable names (recorded by ``_emit_cute_matmul`` on the
    ``DeviceFunction``).  A reduce whose input is one of these is reduced ONCE
    after the loop rather than V-folded — the producer tells us authoritatively
    that the value already accumulates across V-lanes, so we don't re-derive it
    by pattern-matching the AST.
    """
    return _hoist_in_body(body, [0], running_sum_accumulators or set())
